version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /WDL-HuBMAP-salmon-rnaseq/pipeline.wdl
    name: salmon-rnaseq-wdl
  - subclass: CWL
    primaryDescriptorPath: /WDL-HuBMAP-salmon-rnaseq/pipeline.cwl
    name: salmon-rnaseq-cwl
